#!/bin/bash
set -e

#Ansible settings
export ANSIBLE_STDOUT_CALLBACK="community.general.yaml"
export CONTROLLER_HOST=localhost
export CONTROLLER_USERNAME=admin
export CONTROLLER_PASSWORD='ansible123!'
export CONTROLLER_VERIFY_SSL=false

# Playbook run command
CMD="/bin/ansible-playbook /tmp/setup-scripts/controller-setup.yml"

if ! $CMD --tags=check-inventory -vv; then
 echo "FAIL: ${INVENTORY} inventory not found. Remember it's case-sensitive! Please try again."
 exit 1
fi

if ! curl -k https://jbcs-eap/mcm | grep '/addressbook'; then
 echo "FAIL: addressbook application is not deployed in JBoss EAP; Please try again"
 exit 1
fi
