version: "3"
virtualmachines:
- name: control
  image: red-hat-mbu/automation-controller
  shell: /bin/su - rhel -s /bin/bash
  machine_type: n1-standard-1
- name: jbcs-eap
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  machine_type: e2-small
  allow_external_ingress:
  - https
- name: sso1
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  machine_type: e2-small
- name: sso2
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  machine_type: e2-small
