#!/bin/bash

touch /etc/sudoers.d/rhel_sudoers
echo "%rhel ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/rhel_sudoers
cp -a /root/.ssh/* /home/rhel/.ssh/.
chown -R rhel:rhel /home/rhel/.ssh

scp -o StrictHostKeyChecking=no /etc/resolv.conf root@jbcs-eap:/etc/resolv.conf
scp -o StrictHostKeyChecking=no /etc/resolv.conf root@sso1:/etc/resolv.conf
scp -o StrictHostKeyChecking=no /etc/resolv.conf root@sso2:/etc/resolv.conf