#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

touch /etc/sudoers.d/rhel_sudoers
echo "%rhel ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/rhel_sudoers
cp -a /root/.ssh/* /home/rhel/.ssh/.
chown -R rhel:rhel /home/rhel/.ssh

## ^ from getting started controller

dnf config-manager --disable rhui*,google*

sudo bash -c 'cat >/etc/yum.repos.d/centos8-baseos.repo <<EOL
[centos8-baseos]
name=CentOS 8 Stream BaseOS
baseurl=http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os
enabled=1
gpgcheck=0

EOL
cat /etc/yum.repos.d/centos8-baseos.repo'

sudo bash -c 'cat >/etc/yum.repos.d/centos8-appstream.repo <<EOL
[centos8-appstream]
name=CentOS 8 Stream AppStream
baseurl=http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/
enabled=1
gpgcheck=0

EOL
cat /etc/yum.repos.d/centos8-appstream.repo'

dnf clean all
dnf install -y  @postgresql
/usr/bin/postgresql-setup --initdb
systemctl start postgresql
systemctl stop nginx
systemctl stop code-server
setenforce 0

sudo bash -c 'cat >/tmp/setup_postgres.sql <<EOL
create database keycloak;
create user "keycloak-user" with encrypted password '"'"'keycloak-pass'"'"';
grant all privileges on database keycloak to "keycloak-user";
create database addressbook;
create user addressbook with encrypted password '"'"'addressbookpass'"'"';
grant all privileges on database addressbook to addressbook;
EOL
cat /tmp/setup_postgres.sql'
sudo -iu postgres psql < /tmp/setup_postgres.sql

sudo bash -c 'echo "host    all             all             0.0.0.0/0               md5" >> /var/lib/pgsql/data/pg_hba.conf'
sudo bash -c "sed -i '/ident/d' /var/lib/pgsql/data/pg_hba.conf"
sudo bash -c 'echo "listen_addresses = '"'"'*'"'"'"   >> /var/lib/pgsql/data/postgresql.conf'
systemctl restart postgresql

sudo firewall-cmd --permanent --add-port=5432/tcp

sudo cp /tmp/resolv.conf /etc/resolv.conf
