#!/bin/bash
## solve-inventory
echo "This is the 07 solve script"


git config --global user.email "rhel@a4mw.instruqt.local"
git config --global user.name "A4MW Instruqt student"
cd /home/rhel/eap-sso/ && git fetch --all && git stash && git checkout final_solution
cp /home/rhel/jbcs-eap-key.pem /home/rhel/eap-sso/roles/certificates/files/jbcs-eap.key
cp /home/rhel/jbcs-eap.pem /home/rhel/eap-sso/roles/certificates/files/jbcs-eap.crt
git add -A && git commit -m "Add certificates"
git checkout main && git merge -Xtheirs final_solution


#Ansible settings
export ANSIBLE_STDOUT_CALLBACK="community.general.yaml"
export CONTROLLER_HOST=localhost
export CONTROLLER_USERNAME=admin
export CONTROLLER_PASSWORD='ansible123!'
export CONTROLLER_VERIFY_SSL=false

# Playbook run command
/bin/ansible-playbook /tmp/setup-scripts/controller-setup.yml --tags solve-all -vvv
